export const BASE_URL = 'http://localhost:3000/'
export const API_URL = BASE_URL + 'api/'
export const LOGIN_URL = API_URL + 'auth/token'
export const SIGNUP_URL = API_URL + 'users'
export const USER_PROFILE_URL = API_URL + 'users/profile'
